### ISSUE TITLE
关于界面

### ISSUE THREAD

**Issue by DoLolitingyu** [ProductOfAmerica/LoginGUI#1]
界面做的非常好看，可是没有一把叉，如果用作客户端的话怎么退出

**Comment by ProductOfAmerica** [comment]
Sorry, what?

**Comment by TMLAndroid** [comment]
@ProductOfAmerica his mean is the UI you design is very nice but cannot find exit Options

**Comment by ProductOfAmerica** [comment]
Use the loginEventHandler() option. Write your own method.

Pseudo Code:
```java
if (loggedInSuccessfully)
   startMainApplication();
else
   doNothingAndMakeThemTryAgain();
```
