### ISSUE TITLE
toast Garbled

### ISSUE THREAD

**Issue by TMLAndroid** [ProductOfAmerica/LoginGUI#2]
when i show toast as Chinese, i got a Garbled,but Englich is well do

**Comment by ProductOfAmerica** [comment]
To be quite honest, I don't know how to help you. It's also hard to understand (clearly) what your main point is. If you're trying to display Chinese text in the toast and it's not displaying, then try switching from UTF-8 to UTF-16, as UTF-16 supports Chinese but UTF-8 does not.
