### ISSUE TITLE
Logo wont show up

### ISSUE THREAD

**Issue by buymom** [ProductOfAmerica/LoginGUI#3]
Hey, 
The logo wont show up on the login screen. Ive tried using your placeholder logo, and my own. The program runs just fine, but the icon just doesn't pop up.

**Comment by ProductOfAmerica** [comment]
Hey, I will look in to this in a few moments, hang tight.

**Comment by ProductOfAmerica** [comment]
Did you change this parameter here on line 99 of LoginUI.java?

![612607C5-0726-4ADA-A557-1F7099713C90](https://user-images.githubusercontent.com/14712114/67835630-b5515700-faa7-11e9-9c2b-56449fc8a35a.png)

**Comment by buymom** [comment]
Hey sorry for the late reply, but yeah I changed it. I also tried it with
your lumo logo and it still doesn’t work.

**Comment by ProductOfAmerica** [comment]
> Hey sorry for the late reply, but yeah I changed it. I also tried it with your lumo logo and it still doesn’t work.
> […](#)

Is there an error?

**Comment by buymom** [comment]
There was no error (the image just wasnt showing up) but I figured it out.

This statement: label1.setIcon(new ImageIcon(Objects.
requireNonNull(getClass().getClassLoader().getResource("lumo_placeholder.png
")).getFile()));

The getFile() function messes it up as it requests a file twice, Since you
already have the getResource function. Removing it will solve the problem.
